
# Linux driver folder

obj-m += hynitron_touch.o

hynitron_touch-objs	+= hynitron_core.o
hynitron_touch-objs	+= hynitron_i2c.o
hynitron_touch-objs	+= hynitron_esd_check.o
hynitron_touch-objs	+= hynitron_tool_debug.o
hynitron_touch-objs	+= hynitron_update_firmware.o
hynitron_touch-objs	+= hynitron_gesture.o
hynitron_touch-objs	+= hynitron_proximity.o
