#!/bin/sh

case "$1" in
  start)
    printf "start fbdaemon: "
    /opt/lcd/fbdaemon
    echo "OK"
    ;;
  stop)
    printf "stop fbdaemon: "
    killall fbdaemon
    echo "OK"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
