#!/bin/sh

case "$1" in
  start)
    # use all sdcard free space for rootfs
    parted -s /dev/mmcblk0 "resizepart 2 -0"
    # resize root filesystem
    resize2fs /dev/mmcblk0p2
    chmod -x /etc/init.d/S99firstboot
    mv /etc/init.d/S99firstboot /opt/S99firstboot.done
    reboot
    ;;
  stop)
    printf "nop"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
