#!/bin/sh
case "$1" in
  start)
    printf "start loopback: "
    ifconfig lo up
    ifconfig lo 127.0.0.1
    echo "OK"
    ;;
  stop)
    ifconfig lo down
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
