#!/bin/sh

case "$1" in
  start)
    printf "rc.local: "
    sh /etc/rc.local
    echo "OK"
    ;;
  stop)
    printf "nop"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
