#!/bin/sh

if [ "$1" = "start" ]
then
	. /etc/profile
	mkdir -p /boot
	mount -t vfat /dev/mmcblk0p1 /boot
	mount -t configfs configfs /sys/kernel/config
	mount -t debugfs debugfs /sys/kernel/debug
fi
