#!/bin/sh

if [ "$1" = "start" ]
then
	. /etc/profile
	printf "copy config file from /boot: "
	if [ -e /boot/sshd_config ]
	then
		cp -vf /boot/sshd_config /etc/ssh/sshd_config
	fi
	if [ -e /boot/input-event-daemon ]
	then
		chmod 0644 /etc/input-event-daemon.conf
	else
		chmod 0000 /etc/input-event-daemon.conf
	fi
	if [ -e /boot/rc.local ]
	then
		cp -vf /boot/rc.local /etc/rc.local
	fi
	if [ -e /boot/ttyGS0_handler.sh ]
	then
		cp /boot/ttyGS0_handler.sh /etc/ttyGS0_handler.sh
	fi
	if [ -e /boot/console_handler.sh ]
	then
		cp /boot/ttyGS0_handler.sh /etc/ttyGS0_handler.sh
	fi
	if [ -e /boot/alpha ]
	then
		if [ ! -e /mnt/data/sensor_cfg.ini ]
		then
			cp /mnt/data/sensor_cfg.ini.alpha /mnt/data/sensor_cfg.ini
		fi
		# MIPI RX 4N PINMUX MCLK0
		devmem 0x0300116C 32 0x5
		# MIPI RX 0N PINMUX MIPIP RX 0N
		devmem 0x0300118C 32 0x3
		echo " alpha "
	else
		if [ ! -e /mnt/data/sensor_cfg.ini ]
		then
			cp /mnt/data/sensor_cfg.ini.beta /mnt/data/sensor_cfg.ini
		fi
		# MIPI RX 4N PINMUX MIPI RX 4N
		devmem 0x0300116C 32 0x3
		# MIPI RX 0N PINMUX MCLK1
		devmem 0x0300118C 32 0x5
		echo -n " beta "
	fi
	echo "OK"
fi
