#!/bin/sh

if [ "$1" = "start" ]
then
	. /etc/profile
	printf "copy config file from /boot: "
	if [ -e /boot/sshd_config ]
	then
		cp -vf /boot/sshd_config /etc/ssh/sshd_config
	fi
	if [ -e /boot/resolv.conf ]
	then
		rm -rf /etc/resolv.conf
		cp -vf /boot/resolv.conf /etc/resolv.conf
	fi
	if [ -e /boot/input-event-daemon ]
	then
		if [ ! -e /etc/input-event-daemon.conf ]
		then
			cp /etc/input-event-daemon.conf.bak /etc/input-event-daemon.conf
		fi
	else
		if [ -e /etc/input-event-daemon.conf ]
		then
			cp /etc/input-event-daemon.conf /etc/input-event-daemon.conf.bak
			rm /etc/input-event-daemon.conf
		fi
	fi
	if [ -e /boot/rc.local ]
	then
		cp -vf /boot/rc.local /etc/rc.local
	fi
	if [ -e /boot/ttyGS0_handler.sh ]
	then
		cp /boot/ttyGS0_handler.sh /etc/ttyGS0_handler.sh
	fi
	if [ -e /boot/console_handler.sh ]
	then
		cp /boot/console_handler.sh /etc/console_handler.sh
	fi
	if [ -e /boot/alpha ]
	then
		if [ ! -e /mnt/data/sensor_cfg.ini ]
		then
			cp /mnt/data/sensor_cfg.ini.alpha /mnt/data/sensor_cfg.ini
		fi
		if [ $(cat /mnt/data/sensor_cfg.ini | wc -l) -eq 0 ]
		then
			cp /mnt/data/sensor_cfg.ini.beta /mnt/data/sensor_cfg.ini
		fi
		# MIPI RX 4N PINMUX MCLK0
		devmem 0x0300116C 32 0x5
		# MIPI RX 0N PINMUX MIPIP RX 0N
		devmem 0x0300118C 32 0x3
		echo " alpha "
	else
		if [ ! -e /mnt/data/sensor_cfg.ini ]
		then
			cp /mnt/data/sensor_cfg.ini.beta /mnt/data/sensor_cfg.ini
		fi
		if [ $(cat /mnt/data/sensor_cfg.ini | wc -l) -eq 0 ]
		then
			cp /mnt/data/sensor_cfg.ini.beta /mnt/data/sensor_cfg.ini
		fi
		# MIPI RX 4N PINMUX MIPI RX 4N
		devmem 0x0300116C 32 0x3
		# MIPI RX 0N PINMUX MCLK1
		devmem 0x0300118C 32 0x5
		echo -n " beta "
	fi
	if [ -e /boot/kvmtest ]
	then
		cp /mnt/data/sensor_cfg.ini.LT /mnt/data/sensor_cfg.ini
	fi
	echo "OK"
fi
