#!/bin/sh


if [ "$1" = "start" ]
then
	. /etc/profile
	if [ -e /boot/usb.host ]
	then
		echo "usb mode: host"
		echo host > /proc/cviusb/otg_role
	elif [ -e /boot/usb.dev ]
	then
		echo "usb mode: device"
		cd /sys/kernel/config/usb_gadget
		mkdir -p g0
		cd g0
		if [ -e /boot/usb.idVendor ]
		then
			cat /boot/usb.idVendor > idVendor
		else
			echo 0x359F > idVendor
		fi
		if [ -e /boot/usb.idProduct ]
		then
			cat /boot/usb.idProduct > idProduct
		else
			echo 0x2120 > idProduct
		fi
		if [ -e /boot/usb.bcdDevice ]
		then
			cat /boot/usb.bcdDevice > bcdDevice
		else
			echo 0x0300 > bcdDevice
		fi
		if [ -e /boot/usb.bcdUSB ]
		then
			cat /boot/usb.bcdUSB > bcdUSB
		else
			echo 0x0200 > bcdUSB
		fi
		if [ -e /boot/usb.bDeviceClass ]
		then
			cat /boot/usb.bDeviceClass > bDeviceClass
		else
			echo 0xef > bDeviceClass
		fi
		if [ -e /boot/usb.bDeviceSubClass ]
		then
			cat /boot/usb.bDeviceSubClass > bDeviceSubClass
		else
			echo 0x02 > bDeviceSubClass
		fi
		if [ -e /boot/usb.bDeviceProtocol ]
		then
			cat /boot/usb.bDeviceProtocol > bDeviceProtocol
		else
			echo 0x01 > bDeviceProtocol
		fi
		mkdir -p strings/0x409
		if [ -e /boot/usb.serialnumber ]
		then
			cat /boot/usb.serialnumber > strings/0x409/serialnumber
		else
			cat /device_key > strings/0x409/serialnumber
		fi
		if [ -e /boot/usb.manufacturer ]
		then
			cat /boot/usb.manufacturer > strings/0x409/manufacturer
		else
			echo 'sipeed' > strings/0x409/manufacturer
		fi
		if [ -e /boot/usb.product ]
		then
			cat /boot/usb.product > strings/0x409/product
		else
			echo 'licheervnano' > strings/0x409/product
		fi
		mkdir -p configs/c.1
		if [ -e /boot/usb.GS0 ]
		then
			mkdir -p functions/acm.GS0
			rm -rf configs/c.1/acm.GS0
			ln -s functions/acm.GS0 configs/c.1/
		fi

		if [ -e /boot/usb.disk0 ]
		then
			mkdir -p functions/mass_storage.disk0
			rm -rf configs/c.1/mass_storage.disk0
			ln -s functions/mass_storage.disk0 configs/c.1/
			echo 1 > functions/mass_storage.disk0/lun.0/removable
			if [ -e /boot/usb.disk0.ro ]
			then
				echo 1 > functions/mass_storage.disk0/lun.0/ro
				echo 1 > functions/mass_storage.disk0/lun.0/cdrom
			fi
			disk=$(cat /boot/usb.disk0)
			if [ -z "${disk}" ]
			then
				if [ ! -e /mnt/usbdisk.img ]
				then
					dd if=/dev/zero of=/mnt/usbdisk.img bs=1M count=16
					mkfs.vfat /mnt/usbdisk.img
				fi
				echo /mnt/usbdisk.img > functions/mass_storage.disk0/lun.0/file
			else
				cat /boot/usb.disk0 > functions/mass_storage.disk0/lun.0/file
			fi
		fi

		# rndis
		if [ -e /boot/usb.rndis ]
		then
			mkdir -p functions/rndis.usb0
			ln -s functions/rndis.usb0 configs/c.1/
			echo e0 > functions/rndis.usb0/class
			echo 01 > functions/rndis.usb0/subclass
			echo 03 > functions/rndis.usb0/protocol
		fi

		# ncm
		if [ -e /boot/usb.ncm ]
		then
			mkdir -p functions/ncm.usb0
			ln -s functions/ncm.usb0 configs/c.1/
		fi

		ls /sys/class/udc/ | cat > UDC
		echo device > /proc/cviusb/otg_role
	fi
fi

if [ "$1" = "stop" ]
then
	# rndis
	if [ -e /sys/kernel/config/usb_gadget/g0/configs/c.1/rndis.usb0 ]
	then
		unlink /sys/kernel/config/usb_gadget/g0/configs/c.1/rndis.usb0
		rmdir /sys/kernel/config/usb_gadget/g0/functions/rndis.usb0
	fi

	# ncm
	if [ -e /sys/kernel/config/usb_gadget/g0/configs/c.1/ncm.usb0 ]
	then
		unlink /sys/kernel/config/usb_gadget/g0/configs/c.1/ncm.usb0
		rmdir /sys/kernel/config/usb_gadget/g0/functions/ncm.usb0
	fi
	echo '' > /sys/kernel/config/usb_gadget/g0/UDC
	echo host > /proc/cviusb/otg_role
fi

