#!/bin/sh

if [ "$1" = "start" ]
then
	. /etc/profile
	if [ ! -e /boot/alpha ]
	then
		devmem 0x030010AC 32 0x04 # PINMUX PWM10
		blpwm="/sys/class/pwm/pwmchip8/pwm2/"
		if [ ! -e "${blpwm}" ]
		then
			echo 2 > /sys/class/pwm/pwmchip8/export
		fi
		echo 0 > $blpwm/enable
		echo "10000" > ${blpwm}/period # 100KHZ
		panel_value=""
		if [ -e /boot/board ]
		then
			panel_value=$(grep '^panel=' /boot/board | cut -d '=' -f 2)
		elif [ -e /boot/uEnv.txt ]
		then
			panel_value=$(grep '^panel=' /boot/uEnv.txt | cut -d '=' -f 2)
		fi
		if [ "$panel_value" = "st7701_hd228001c31" ]
		then
			echo "2000" > ${blpwm}/duty_cycle # 20%
		else
			echo "9000" > ${blpwm}/duty_cycle
		fi
		echo 1 > $blpwm/enable
	fi
	exit 0
fi
