#!/bin/sh

if [ "$1" = "start" ]
then
	. /etc/profile
	panel_value=$(grep '^panel=' /boot/uEnv.txt | cut -d '=' -f 2)
	if [ "$panel_value" = "st7701_lct024bsi20" ]
	then
		echo "load cst7xx touchscreen driver"
		insmod /mnt/system/ko/hynitron_touch_new.ko
	elif [ "$panel_value" = "st7701_hd228001c31" ]
	then
		echo "load cst3xx touchscreen driver"
		insmod /mnt/system/ko/hynitron_touch.ko
	fi
	if [ -e /boot/gt9xx ]
	then
		echo "load gt9xx touchscreen driver"
		insmod /mnt/system/ko/3rd/gt9xx.ko
	fi
	exit 0
fi
