#!/bin/sh

if [ "$1" = "start" ]
then
	. /etc/profile
	printf "load wifi kernel module: "
	cd /mnt/system/ko/
	insmod cfg80211.ko
	insmod 3rd/aic8800_bsp.ko
	insmod 3rd/aic8800_fdrv.ko
	insmod 3rd/8733bs.ko
	echo "OK"
	exit 0
fi
