#!/bin/sh

. /etc/profile

gen_dnsmasq_conf() {
	interface=${1}
	ipv4_prefix=${2}
	echo "interface=${interface}"
	echo "dhcp-range=${ipv4_prefix}.50,${ipv4_prefix}.150,255.255.255.0,120h"
}

start() {
	if [ ! -e /boot/rndis.nodhcpd ]
	then
		if [ -e /boot/rndis.ipv4_prefix ]
		then
			ipv4_prefix=`cat /boot/rndis.ipv4_prefix`
		else
			id2=$(printf "%d" 0x$(sha512sum /sys/class/cvi-base/base_uid | head -c 2))
			id3=$(printf "%d" 0x$(sha512sum /sys/class/cvi-base/base_uid | head -c 4 | tail -c 2))
			if [ "$id2" -ge 255 ]
			then
				id2=254
			fi
			if [ "$id3" -ge 255 ]
			then
				id3=254
			fi
			ipv4_prefix=10.$id2.$id3
		fi
		gen_dnsmasq_conf usb0 "${ipv4_prefix}"  > /etc/dnsmasq.conf
		ip addr add $ipv4_prefix.1/24 dev usb0
	fi
}

stop() {
	echo ""
}

restart() {
	start
	stop
}

if [ "${1}" = "start" ]
then
	start
elif [ "${1}" = "stop" ]
then
	stop
elif [ "${1}" = "restart" ]
then
	restart
fi
