#!/bin/sh

. /etc/profile

gen_udhcpd_conf() {
	interface=${1}
	ipv4_prefix=${2}
	echo "start ${ipv4_prefix}.100"
	echo "end ${ipv4_prefix}.200"
	echo "interface ${interface}"
	echo "pidfile /var/run/udhcpd.${interface}.pid"
	echo "lease_file /var/lib/misc/udhcpd.${interface}.leases"
	echo "option subnet 255.255.255.0"
	echo "option lease 864000"
}

start() {
	if [ -e /boot/usb.rndis0 ]
	then
		printf "start usb rndis: "
		if [ ! -e /boot/rndis.nodhcpd ]
		then
			if [ -e /boot/rndis.ipv4_prefix ]
			then
				ipv4_prefix=`cat /boot/rndis.ipv4_prefix`
			else
				id2=$(printf "%d" 0x$(sha512sum /sys/class/cvi-base/base_uid | head -c 2))
				id3=$(printf "%d" 0x$(sha512sum /sys/class/cvi-base/base_uid | head -c 4 | tail -c 2))
				if [ "$id2" = "$id3" ]
				then
					id2=$((id2 + 1))
				fi
				if [ "$id2" -ge 255 ]
				then
					id2=253
				fi
				if [ "$id3" -ge 255 ]
				then
					id3=254
				fi
				ipv4_prefix=10.$id2.$id3
			fi
			gen_udhcpd_conf usb0 "${ipv4_prefix}"  > /etc/udhcpd.usb0.conf
			ip addr add $ipv4_prefix.1/24 dev usb0
			udhcpd -S /etc/udhcpd.usb0.conf
		fi
		echo "ok"
	fi
}

stop() {
	kill `cat /var/run/udhcpd.usb0.pid`
        rm /var/run/udhcpd.usb0.pid
}

restart() {
	start
	stop
}

if [ "${1}" = "start" ]
then
	start
elif [ "${1}" = "stop" ]
then
	stop
elif [ "${1}" = "restart" ]
then
	restart
fi
