#!/bin/sh

if [ "$1" = "start" ]
then
	. /etc/profile
	panel_value=$(grep '^panel=' /boot/uEnv.txt | cut -d '=' -f 2)
	if [ "$panel_value" = "MaixCam_Pro" ]
	then
		echo "init axp2101 pmu"
		exec /usr/bin/axp2101
	fi
	exit 0
fi
