#!/bin/sh

case "$1" in
  start)
    printf "load kernel module: "
    insmod /mnt/system/ko/cv181x_sys.ko
    insmod /mnt/system/ko/cv181x_base.ko
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    printf "nop"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
