obj-m += hynitron_touch_new.o

hynitron_touch_new-objs += hyn_core.o hyn_lib/hyn_i2c.o hyn_lib/hyn_spi.o hyn_lib/hyn_ts_ext.o hyn_lib/hyn_fs_node.o
hynitron_touch_new-objs += hyn_lib/hyn_tool.o
hynitron_touch_new-objs += hyn_lib/hyn_gesture.o
hynitron_touch_new-objs += hyn_lib/hyn_prox.o
hynitron_touch_new-objs += hyn_chips/hyn_cst66xx.o
hynitron_touch_new-objs += hyn_chips/hyn_cst3240.o
hynitron_touch_new-objs += hyn_chips/hyn_cst92xx.o
hynitron_touch_new-objs += hyn_chips/hyn_cst3xx.o
hynitron_touch_new-objs += hyn_chips/hyn_cst1xx.o  
hynitron_touch_new-objs += hyn_chips/hyn_cst7xx.o
hynitron_touch_new-objs += hyn_chips/hyn_cst8xxT.o
