// $Module: reg_isp_rdma $
// $RegisterBank Version: V 1.0.00 $
// $Author: Siwi $
// $Date: Sun, 26 Sep 2021 04:20:44 PM $
//

//GEN REG ADDR/OFFSET/MASK
#define  ISP_RDMA_SHADOW_RD_SEL  0x0
#define  ISP_RDMA_IP_DISABLE  0x4
#define  ISP_RDMA_NORM_STATUS0  0x10
#define  ISP_RDMA_NORM_STATUS1  0x14
#define  ISP_RDMA_NORM_PERF  0x20
#define  ISP_RDMA_REG_SHADOW_RD_SEL   0x0
#define  ISP_RDMA_REG_SHADOW_RD_SEL_OFFSET 0
#define  ISP_RDMA_REG_SHADOW_RD_SEL_MASK   0x1
#define  ISP_RDMA_REG_SHADOW_RD_SEL_BITS   0x1
#define  ISP_RDMA_REG_IP_DISABLE   0x4
#define  ISP_RDMA_REG_IP_DISABLE_OFFSET 0
#define  ISP_RDMA_REG_IP_DISABLE_MASK   0xffffffff
#define  ISP_RDMA_REG_IP_DISABLE_BITS   0x20
#define  ISP_RDMA_REG_ABORT_DONE   0x10
#define  ISP_RDMA_REG_ABORT_DONE_OFFSET 0
#define  ISP_RDMA_REG_ABORT_DONE_MASK   0x1
#define  ISP_RDMA_REG_ABORT_DONE_BITS   0x1
#define  ISP_RDMA_REG_ERROR_AXI   0x10
#define  ISP_RDMA_REG_ERROR_AXI_OFFSET 4
#define  ISP_RDMA_REG_ERROR_AXI_MASK   0x10
#define  ISP_RDMA_REG_ERROR_AXI_BITS   0x1
#define  ISP_RDMA_REG_ERROR_ID   0x10
#define  ISP_RDMA_REG_ERROR_ID_OFFSET 8
#define  ISP_RDMA_REG_ERROR_ID_MASK   0x1f00
#define  ISP_RDMA_REG_ERROR_ID_BITS   0x5
#define  ISP_RDMA_REG_DMA_VERSION   0x10
#define  ISP_RDMA_REG_DMA_VERSION_OFFSET 16
#define  ISP_RDMA_REG_DMA_VERSION_MASK   0xffff0000
#define  ISP_RDMA_REG_DMA_VERSION_BITS   0x10
#define  ISP_RDMA_REG_ID_DONE   0x14
#define  ISP_RDMA_REG_ID_DONE_OFFSET 0
#define  ISP_RDMA_REG_ID_DONE_MASK   0xffffffff
#define  ISP_RDMA_REG_ID_DONE_BITS   0x20
#define  ISP_RDMA_REG_BWLWIN   0x20
#define  ISP_RDMA_REG_BWLWIN_OFFSET 0
#define  ISP_RDMA_REG_BWLWIN_MASK   0x3ff
#define  ISP_RDMA_REG_BWLWIN_BITS   0xa
#define  ISP_RDMA_REG_BWLTXN   0x20
#define  ISP_RDMA_REG_BWLTXN_OFFSET 10
#define  ISP_RDMA_REG_BWLTXN_MASK   0xfc00
#define  ISP_RDMA_REG_BWLTXN_BITS   0x6
