// $Module: reg_ive_intg $
// $RegisterBank Version: V 1.0.00 $
// $Author:  $
// $Date: Wed, 03 Nov 2021 05:10:29 PM $
//

//GEN REG ADDR/OFFSET/MASK
#define  IVE_INTG_REG_0  0x0
#define  IVE_INTG_REG_1  0x4
#define  IVE_INTG_REG_2  0x8
#define  IVE_INTG_REG_IVE_INTG_ENABLE   0x0
#define  IVE_INTG_REG_IVE_INTG_ENABLE_OFFSET 0
#define  IVE_INTG_REG_IVE_INTG_ENABLE_MASK   0x1
#define  IVE_INTG_REG_IVE_INTG_ENABLE_BITS   0x1
#define  IVE_INTG_REG_SHDW_SEL   0x0
#define  IVE_INTG_REG_SHDW_SEL_OFFSET 1
#define  IVE_INTG_REG_SHDW_SEL_MASK   0x2
#define  IVE_INTG_REG_SHDW_SEL_BITS   0x1
#define  IVE_INTG_REG_SOFTRST   0x0
#define  IVE_INTG_REG_SOFTRST_OFFSET 2
#define  IVE_INTG_REG_SOFTRST_MASK   0x4
#define  IVE_INTG_REG_SOFTRST_BITS   0x1
#define  IVE_INTG_REG_IVE_INTG_TILE_NM   0x0
#define  IVE_INTG_REG_IVE_INTG_TILE_NM_OFFSET 4
#define  IVE_INTG_REG_IVE_INTG_TILE_NM_MASK   0xf0
#define  IVE_INTG_REG_IVE_INTG_TILE_NM_BITS   0x4
#define  IVE_INTG_REG_IVE_INTG_CTRL   0x0
#define  IVE_INTG_REG_IVE_INTG_CTRL_OFFSET 8
#define  IVE_INTG_REG_IVE_INTG_CTRL_MASK   0x300
#define  IVE_INTG_REG_IVE_INTG_CTRL_BITS   0x2
#define  IVE_INTG_REG_IVE_INTG_STRIDE   0x4
#define  IVE_INTG_REG_IVE_INTG_STRIDE_OFFSET 0
#define  IVE_INTG_REG_IVE_INTG_STRIDE_MASK   0xffff
#define  IVE_INTG_REG_IVE_INTG_STRIDE_BITS   0x10
#define  IVE_INTG_REG_IVE_INTG_MEM_ADDR   0x8
#define  IVE_INTG_REG_IVE_INTG_MEM_ADDR_OFFSET 0
#define  IVE_INTG_REG_IVE_INTG_MEM_ADDR_MASK   0xffffffff
#define  IVE_INTG_REG_IVE_INTG_MEM_ADDR_BITS   0x20
